In [11]:
%matplotlib inline
import numpy as np
import pylab

In [12]:
A = np.random.randint(0, 10, (4, 3))
A

array([[2, 8, 6],
       [5, 3, 1],
       [7, 7, 5],
       [7, 1, 8]])

In [13]:
for i in range(A.shape[1]):
    print(np.sum(A[:,i]))

21
19
20

In [22]:
data = np.loadtxt('krdu-2001-2010.csv', delimiter=',')
data
ymd = data[:,:3].astype(int)
ymd

array([[2001,    1,    1],
       [2001,    1,    2],
       [2001,    1,    3],
       ...,
       [2010,   12,   29],
       [2010,   12,   30],
       [2010,   12,   31]])

In [24]:
monthly_total = np.zeros(13)
monthly_count = np.zeros(13)
for i in range(len(data)):
    month = ymd[i, 1]
    monthly_total[month] = monthly_total[month] + data[i, 3]
    monthly_count[month] = monthly_count[month] +1
monthly_total[1:] / monthly_count[1:]

array([ 0.08339961,  0.08695011,  0.14141639,  0.09358393,  0.09587416,
        0.13546837,  0.15607261,  0.15245994,  0.14713597,  0.10044371,
        0.1180842 ,  0.11385294])

In [18]:
import urllib.request
urllib.request.urlretrieve('https://wwwx.cs.unc.edu/Courses/comp116-f17/media/krdu-2001-2010.csv', 'krdu-2001-2010.csv')

('krdu-2001-2010.csv', <http.client.HTTPMessage at 0x117ae3898>)

In [25]:
monthly_total = np.zeros(13)
monthly_count = np.zeros(13)
for i in range(len(data)):
    month = ymd[i, 1]
    monthly_total[month] = monthly_total[month] + data[i, 3]
    monthly_count[month] = monthly_count[month] + 1
    if i % 100 == 0:
        print('i=', i, 'month=', month)
        print('mt=', monthly_total)
        print('mc=', monthly_count)

i= 0 month= 1
mt= [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
mc= [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
i= 100 month= 4
mt= [ 0.       1.30306  2.34247  7.11368  0.80713  0.       0.       0.       0.
  0.       0.       0.       0.     ]
mc= [  0.  31.  28.  31.  11.   0.   0.   0.   0.   0.   0.   0.   0.]
i= 200 month= 7
mt= [ 0.       1.30306  2.34247  7.11368  1.72054  3.53152  4.5395   1.24411
  0.       0.       0.       0.       0.     ]
mc= [  0.  31.  28.  31.  30.  31.  30.  20.   0.   0.   0.   0.   0.]
i= 300 month= 10
mt= [ 0.       1.30306  2.34247  7.11368  1.72054  3.53152  4.5395   4.13791
  4.87766  0.86221  1.86259  0.       0.     ]
mc= [  0.  31.  28.  31.  30.  31.  30.  31.  31.  30.  28.   0.   0.]
i= 400 month= 2
mt= [ 0.       7.27504  2.34247  7.11368  1.72054  3.53152  4.5395   4.13791
  4.87766  0.86221  1.86259  0.50001  2.01582]
mc= [  0.  62.  33.  31.  30.  31.  30.  31.  31.  30.  31.  30.  31.]
i= 500 month= 5
mt= [  0.        7.27504   3.61016  11.29863   2.85444   4.40557   4.5395
   4.13791   4.87766   0.86221   1.86259   0.50001   2.01582]
mc= [  0.  62.  56.  62.  60.  47.  30.  31.  31.  30.  31.  30.  31.]
i= 600 month= 8
mt= [  0.        7.27504   3.61016  11.29863   2.85444   4.66939   7.2874
   8.90206   5.79893   0.86221   1.86259   0.50001   2.01582]
mc= [  0.  62.  56.  62.  60.  62.  60.  62.  55.  30.  31.  30.  31.]
i= 700 month= 12
mt= [  0.        7.27504   3.61016  11.29863   2.85444   4.66939   7.2874
   8.90206   9.59058   4.35404  11.22108   4.05868   2.01582]
mc= [  0.  62.  56.  62.  60.  62.  60.  62.  62.  60.  62.  60.  33.]
i= 800 month= 3
mt= [  0.        9.11357   8.25616  12.63729   2.85444   4.66939   7.2874
   8.90206   9.59058   4.35404  11.22108   4.05868   7.05538]
mc= [  0.  93.  84.  74.  60.  62.  60.  62.  62.  60.  62.  60.  62.]
i= 900 month= 6
mt= [  0.        9.11357   8.25616  16.53513   7.32262   8.95338  11.00396
   8.90206   9.59058   4.35404  11.22108   4.05868   7.05538]
mc= [  0.  93.  84.  93.  90.  93.  80.  62.  62.  60.  62.  60.  62.]
i= 1000 month= 9
mt= [  0.        9.11357   8.25616  16.53513   7.32262   8.95338  11.44486
  13.30351  18.16078   8.82232  11.22108   4.05868   7.05538]
mc= [  0.  93.  84.  93.  90.  93.  90.  93.  93.  88.  62.  60.  62.]
i= 1100 month= 1
mt= [  0.        9.38527   8.25616  16.53513   7.32262   8.95338  11.44486
  13.30351  18.16078   8.82232  13.84309   5.86969  10.57519]
mc= [  0.  99.  84.  93.  90.  93.  90.  93.  93.  90.  93.  90.  93.]
i= 1200 month= 4
mt= [  0.       10.34593  11.57504  19.84617   8.64936   8.95338  11.44486
  13.30351  18.16078   8.82232  13.84309   5.86969  10.57519]
mc= [   0.  124.  113.  124.  105.   93.   90.   93.   93.   90.   93.   90.
   93.]
i= 1300 month= 7
mt= [  0.       10.34593  11.57504  19.84617   9.03916  12.39027  15.66499
  18.09155  18.16078   8.82232  13.84309   5.86969  10.57519]
mc= [   0.  124.  113.  124.  120.  124.  120.  117.   93.   90.   93.   90.
   93.]
i= 1400 month= 11
mt= [  0.       10.34593  11.57504  19.84617   9.03916  12.39027  15.66499
  21.47354  27.42485  13.31431  16.35495   5.86969  10.57519]
mc= [   0.  124.  113.  124.  120.  124.  120.  124.  124.  120.  124.   91.
   93.]
i= 1500 month= 2
mt= [  0.       12.98749  12.10654  19.84617   9.03916  12.39027  15.66499
  21.47354  27.42485  13.31431  16.35495   9.76376  12.05544]
mc= [   0.  155.  122.  124.  120.  124.  120.  124.  124.  120.  124.  120.
  124.]
i= 1600 month= 5
mt= [  0.       12.98749  13.86642  23.39737  12.17334  14.37053  15.66499
  21.47354  27.42485  13.31431  16.35495   9.76376  12.05544]
mc= [   0.  155.  141.  155.  150.  144.  120.  124.  124.  120.  124.  120.
  124.]
i= 1700 month= 8
mt= [  0.       12.98749  13.86642  23.39737  12.17334  14.46108  17.17291
  29.11549  31.17236  13.31431  16.35495   9.76376  12.05544]
mc= [   0.  155.  141.  155.  150.  155.  150.  155.  152.  120.  124.  120.
  124.]
i= 1800 month= 12
mt= [  0.       12.98749  13.86642  23.39737  12.17334  14.46108  17.17291
  29.11549  31.32196  14.1371   18.42179  13.4877   13.57076]
mc= [   0.  155.  141.  155.  150.  155.  150.  155.  155.  150.  155.  150.
  130.]
i= 1900 month= 3
mt= [  0.       15.0583   15.52006  23.59025  12.17334  14.46108  17.17291
  29.11549  31.32196  14.1371   18.42179  13.4877   16.29865]
mc= [   0.  186.  169.  171.  150.  155.  150.  155.  155.  150.  155.  150.
  155.]
i= 2000 month= 6
mt= [  0.       15.0583   15.52006  24.65322  17.11109  16.04391  26.12598
  29.11549  31.32196  14.1371   18.42179  13.4877   16.29865]
mc= [   0.  186.  169.  186.  180.  186.  174.  155.  155.  150.  155.  150.
  155.]
i= 2100 month= 10
mt= [  0.       15.0583   15.52006  24.65322  17.11109  16.04391  27.62588
  32.43018  35.74297  22.66447  18.42179  13.4877   16.29865]
mc= [   0.  186.  169.  186.  180.  186.  180.  186.  186.  180.  157.  150.
  155.]
i= 2200 month= 1
mt= [  0.       17.0032   15.52006  24.65322  17.11109  16.04391  27.62588
  32.43018  35.74297  22.66447  21.89019  22.52319  19.29875]
mc= [   0.  196.  169.  186.  180.  186.  180.  186.  186.  180.  186.  180.
  186.]
i= 2300 month= 4
mt= [  0.       18.17244  17.26417  28.17709  20.74108  16.04391  27.62588
  32.43018  35.74297  22.66447  21.89019  22.52319  19.29875]
mc= [   0.  217.  197.  217.  200.  186.  180.  186.  186.  180.  186.  180.
  186.]
i= 2400 month= 7
mt= [  0.       18.17244  17.26417  28.17709  20.99308  17.47693  32.09785
  37.24092  35.74297  22.66447  21.89019  22.52319  19.29875]
mc= [   0.  217.  197.  217.  210.  217.  210.  215.  186.  180.  186.  180.
  186.]
i= 2500 month= 11
mt= [  0.       18.17244  17.26417  28.17709  20.99308  17.47693  32.09785
  37.37082  36.65638  24.88447  26.54722  22.52319  19.29875]
mc= [   0.  217.  197.  217.  210.  217.  210.  217.  217.  210.  217.  186.
  186.]
i= 2600 month= 2
mt= [  0.       19.43224  19.30748  28.17709  20.99308  17.47693  32.09785
  37.37082  36.65638  24.88447  26.54722  22.99958  23.7512 ]
mc= [   0.  248.  211.  217.  210.  217.  210.  217.  217.  210.  217.  210.
  217.]
i= 2700 month= 5
mt= [  0.       19.43224  20.43339  33.705    24.91391  20.42961  32.09785
  37.37082  36.65638  24.88447  26.54722  22.99958  23.7512 ]
mc= [   0.  248.  226.  248.  240.  241.  210.  217.  217.  210.  217.  210.
  217.]
i= 2800 month= 9
mt= [  0.       19.43224  20.43339  33.705    24.91391  20.59891  36.1803
  43.32745  42.56968  24.88447  26.54722  22.99958  23.7512 ]
mc= [   0.  248.  226.  248.  240.  248.  240.  248.  248.  211.  217.  210.
  217.]
i= 2900 month= 12
mt= [  0.       19.43224  20.43339  33.705    24.91391  20.59891  36.1803
  43.32745  42.56968  34.12818  27.7204   27.05074  23.88113]
mc= [   0.  248.  226.  248.  240.  248.  240.  248.  248.  240.  248.  240.
  227.]
i= 3000 month= 3
mt= [  0.       21.96377  22.08697  38.5672   24.91391  20.59891  36.1803
  43.32745  42.56968  34.12818  27.7204   27.05074  26.81063]
mc= [   0.  279.  254.  268.  240.  248.  240.  248.  248.  240.  248.  240.
  248.]
i= 3100 month= 6
mt= [  0.       21.96377  22.08697  40.53561  26.60288  24.72879  38.52281
  43.32745  42.56968  34.12818  27.7204   27.05074  26.81063]
mc= [   0.  279.  254.  279.  270.  279.  268.  248.  248.  240.  248.  240.
  248.]
i= 3200 month= 10
mt= [  0.       21.96377  22.08697  40.53561  26.60288  24.72879  38.52281
  45.48499  44.22719  37.47888  27.83064  27.05074  26.81063]
mc= [   0.  279.  254.  279.  270.  279.  270.  279.  279.  270.  254.  240.
  248.]
i= 3300 month= 1
mt= [  0.       22.01495  22.08697  40.53561  26.60288  24.72879  38.52281
  45.48499  44.22719  37.47888  28.82281  33.96854  32.9007 ]
mc= [   0.  293.  254.  279.  270.  279.  270.  279.  279.  270.  279.  270.
  279.]
i= 3400 month= 4
mt= [  0.       25.85388  24.51993  43.83908  27.78388  24.72879  38.52281
  45.48499  44.22719  37.47888  28.82281  33.96854  32.9007 ]
mc= [   0.  310.  282.  310.  294.  279.  270.  279.  279.  270.  279.  270.
  279.]
i= 3500 month= 8
mt= [  0.       25.85388  24.51993  43.83908  28.07518  29.72099  40.64051
  48.38251  44.32562  37.47888  28.82281  33.96854  32.9007 ]
mc= [   0.  310.  282.  310.  300.  310.  300.  310.  281.  270.  279.  270.
  279.]
i= 3600 month= 11
mt= [  0.       25.85388  24.51993  43.83908  28.07518  29.72099  40.64051
  48.38251  47.26258  44.14079  31.13755  34.87013  32.9007 ]
mc= [   0.  310.  282.  310.  300.  310.  300.  310.  310.  300.  310.  280.
  279.]

In [26]:
data[:5]

array([[  2.00100000e+03,   1.00000000e+00,   1.00000000e+00,
          0.00000000e+00],
       [  2.00100000e+03,   1.00000000e+00,   2.00000000e+00,
          0.00000000e+00],
       [  2.00100000e+03,   1.00000000e+00,   3.00000000e+00,
          0.00000000e+00],
       [  2.00100000e+03,   1.00000000e+00,   4.00000000e+00,
          0.00000000e+00],
       [  2.00100000e+03,   1.00000000e+00,   5.00000000e+00,
          0.00000000e+00]])